server:
  port: 8888

endpoints:
  mappings:
    sensitive: false

spring:
  cloud:
    config:
      server:
        git:
          uri: file://${HOME}/Documents/Projects/spring-cloud/spring-cloud-gs-config-repo
          search-paths: '{application}'
